apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization 
metadata:
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
  serviceMesh:
    managementState: Removed
  trustedCABundle:
    managementState: Managed
    customCABundle: ""

# vim: tabstop=2 shiftwidth=2 softtabstop=2 expandtab :
